-keeppackagenames **
-keep class skip.** { *; }
-keep class tools.skip.** { *; }
-keep class kotlin.jvm.functions.** {*;}
-keep class com.sun.jna.** { *; }
-dontwarn java.awt.**
-keep class * implements com.sun.jna.** { *; }
-keep class * implements skip.bridge.** { *; }
-keep class **._ModuleBundleAccessor_* { *; }
-keep class pi.ckadmin.** { *; }
-dontwarn kotlin.reflect.full.KClasses
-dontwarn kotlin.reflect.full.KTypes
-dontwarn kotlin.reflect.jvm.KTypesJvm
